// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_0zP5aiY9JMSSzZ53xGHMJi4g3p5uDM8',
    appId: '1:790539520733:web:0a3c72b701e263d53be934',
    messagingSenderId: '790539520733',
    projectId: 'metroapp-46e3e',
    authDomain: 'metroapp-46e3e.firebaseapp.com',
    storageBucket: 'metroapp-46e3e.firebasestorage.app',
    measurementId: 'G-J7H1ZVCMCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwZ0rbWDH-cKAo8pkSdmnuTNkYszvfU9s',
    appId: '1:790539520733:android:514f10d5074889d23be934',
    messagingSenderId: '790539520733',
    projectId: 'metroapp-46e3e',
    storageBucket: 'metroapp-46e3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVuigh2WQCMDgpVW0EvOJifkEOM8zCqsY',
    appId: '1:790539520733:ios:cb4f64b0f8da015e3be934',
    messagingSenderId: '790539520733',
    projectId: 'metroapp-46e3e',
    storageBucket: 'metroapp-46e3e.firebasestorage.app',
    iosBundleId: 'com.example.mrts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVuigh2WQCMDgpVW0EvOJifkEOM8zCqsY',
    appId: '1:790539520733:ios:cb4f64b0f8da015e3be934',
    messagingSenderId: '790539520733',
    projectId: 'metroapp-46e3e',
    storageBucket: 'metroapp-46e3e.firebasestorage.app',
    iosBundleId: 'com.example.mrts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_0zP5aiY9JMSSzZ53xGHMJi4g3p5uDM8',
    appId: '1:790539520733:web:4a1b0835171a84083be934',
    messagingSenderId: '790539520733',
    projectId: 'metroapp-46e3e',
    authDomain: 'metroapp-46e3e.firebaseapp.com',
    storageBucket: 'metroapp-46e3e.firebasestorage.app',
    measurementId: 'G-7VJMD302D1',
  );
}
